// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: wire.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame wraps every message on the wire. The oneof ensures type-safe dispatch.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Frame_Auth
	//	*Frame_AuthOk
	//	*Frame_AuthError
	//	*Frame_Request
	//	*Frame_Response
	//	*Frame_ForwardError
	//	*Frame_Ping
	//	*Frame_Pong
	//	*Frame_DashTokenReq
	//	*Frame_DashTokenResp
	Payload       isFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetPayload() isFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetAuth() *Auth {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *Frame) GetAuthOk() *AuthOK {
	if x != nil {
		if x, ok := x.Payload.(*Frame_AuthOk); ok {
			return x.AuthOk
		}
	}
	return nil
}

func (x *Frame) GetAuthError() *AuthError {
	if x != nil {
		if x, ok := x.Payload.(*Frame_AuthError); ok {
			return x.AuthError
		}
	}
	return nil
}

func (x *Frame) GetRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Frame) GetResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Frame) GetForwardError() *ForwardError {
	if x != nil {
		if x, ok := x.Payload.(*Frame_ForwardError); ok {
			return x.ForwardError
		}
	}
	return nil
}

func (x *Frame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Frame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Frame) GetDashTokenReq() *DashboardTokenReq {
	if x != nil {
		if x, ok := x.Payload.(*Frame_DashTokenReq); ok {
			return x.DashTokenReq
		}
	}
	return nil
}

func (x *Frame) GetDashTokenResp() *DashboardTokenResp {
	if x != nil {
		if x, ok := x.Payload.(*Frame_DashTokenResp); ok {
			return x.DashTokenResp
		}
	}
	return nil
}

type isFrame_Payload interface {
	isFrame_Payload()
}

type Frame_Auth struct {
	Auth *Auth `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type Frame_AuthOk struct {
	AuthOk *AuthOK `protobuf:"bytes,2,opt,name=auth_ok,json=authOk,proto3,oneof"`
}

type Frame_AuthError struct {
	AuthError *AuthError `protobuf:"bytes,3,opt,name=auth_error,json=authError,proto3,oneof"`
}

type Frame_Request struct {
	Request *HttpRequest `protobuf:"bytes,4,opt,name=request,proto3,oneof"`
}

type Frame_Response struct {
	Response *HttpResponse `protobuf:"bytes,5,opt,name=response,proto3,oneof"`
}

type Frame_ForwardError struct {
	ForwardError *ForwardError `protobuf:"bytes,6,opt,name=forward_error,json=forwardError,proto3,oneof"`
}

type Frame_Ping struct {
	Ping *Ping `protobuf:"bytes,7,opt,name=ping,proto3,oneof"`
}

type Frame_Pong struct {
	Pong *Pong `protobuf:"bytes,8,opt,name=pong,proto3,oneof"`
}

type Frame_DashTokenReq struct {
	DashTokenReq *DashboardTokenReq `protobuf:"bytes,9,opt,name=dash_token_req,json=dashTokenReq,proto3,oneof"`
}

type Frame_DashTokenResp struct {
	DashTokenResp *DashboardTokenResp `protobuf:"bytes,10,opt,name=dash_token_resp,json=dashTokenResp,proto3,oneof"`
}

func (*Frame_Auth) isFrame_Payload() {}

func (*Frame_AuthOk) isFrame_Payload() {}

func (*Frame_AuthError) isFrame_Payload() {}

func (*Frame_Request) isFrame_Payload() {}

func (*Frame_Response) isFrame_Payload() {}

func (*Frame_ForwardError) isFrame_Payload() {}

func (*Frame_Ping) isFrame_Payload() {}

func (*Frame_Pong) isFrame_Payload() {}

func (*Frame_DashTokenReq) isFrame_Payload() {}

func (*Frame_DashTokenResp) isFrame_Payload() {}

type DashboardTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardTokenReq) Reset() {
	*x = DashboardTokenReq{}
	mi := &file_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardTokenReq) ProtoMessage() {}

func (x *DashboardTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardTokenReq.ProtoReflect.Descriptor instead.
func (*DashboardTokenReq) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

type DashboardTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // one-time token, valid 5 minutes
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`     // full URL to open in browser
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardTokenResp) Reset() {
	*x = DashboardTokenResp{}
	mi := &file_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardTokenResp) ProtoMessage() {}

func (x *DashboardTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardTokenResp.ProtoReflect.Descriptor instead.
func (*DashboardTokenResp) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DashboardTokenResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Subdomain     string                 `protobuf:"bytes,2,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{3}
}

func (x *Auth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Auth) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *Auth) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AuthOK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subdomain     string                 `protobuf:"bytes,1,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOK) Reset() {
	*x = AuthOK{}
	mi := &file_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOK) ProtoMessage() {}

func (x *AuthOK) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOK.ProtoReflect.Descriptor instead.
func (*AuthOK) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{4}
}

func (x *AuthOK) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *AuthOK) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

type AuthError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthError) Reset() {
	*x = AuthError{}
	mi := &file_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthError) ProtoMessage() {}

func (x *AuthError) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthError.ProtoReflect.Descriptor instead.
func (*AuthError) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{5}
}

func (x *AuthError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`                         // raw bytes, zstd-compressed if flag set
	Compressed    bool                   `protobuf:"varint,7,opt,name=compressed,proto3" json:"compressed,omitempty"`            // true if body is zstd-compressed
	ReplayOf      string                 `protobuf:"bytes,8,opt,name=replay_of,json=replayOf,proto3" json:"replay_of,omitempty"` // original request ID if this is a replay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_wire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{6}
}

func (x *HttpRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpRequest) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

func (x *HttpRequest) GetReplayOf() string {
	if x != nil {
		return x.ReplayOf
	}
	return ""
}

type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // raw bytes, zstd-compressed if flag set
	Compressed    bool                   `protobuf:"varint,5,opt,name=compressed,proto3" json:"compressed,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_wire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{7}
}

func (x *HttpResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpResponse) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

func (x *HttpResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ForwardError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardError) Reset() {
	*x = ForwardError{}
	mi := &file_wire_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardError) ProtoMessage() {}

func (x *ForwardError) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardError.ProtoReflect.Descriptor instead.
func (*ForwardError) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{8}
}

func (x *ForwardError) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ForwardError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_wire_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{9}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_wire_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{10}
}

var File_wire_proto protoreflect.FileDescriptor

const file_wire_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wire.proto\x12\apipepie\"\x92\x04\n" +
	"\x05Frame\x12#\n" +
	"\x04auth\x18\x01 \x01(\v2\r.pipepie.AuthH\x00R\x04auth\x12*\n" +
	"\aauth_ok\x18\x02 \x01(\v2\x0f.pipepie.AuthOKH\x00R\x06authOk\x123\n" +
	"\n" +
	"auth_error\x18\x03 \x01(\v2\x12.pipepie.AuthErrorH\x00R\tauthError\x120\n" +
	"\arequest\x18\x04 \x01(\v2\x14.pipepie.HttpRequestH\x00R\arequest\x123\n" +
	"\bresponse\x18\x05 \x01(\v2\x15.pipepie.HttpResponseH\x00R\bresponse\x12<\n" +
	"\rforward_error\x18\x06 \x01(\v2\x15.pipepie.ForwardErrorH\x00R\fforwardError\x12#\n" +
	"\x04ping\x18\a \x01(\v2\r.pipepie.PingH\x00R\x04ping\x12#\n" +
	"\x04pong\x18\b \x01(\v2\r.pipepie.PongH\x00R\x04pong\x12B\n" +
	"\x0edash_token_req\x18\t \x01(\v2\x1a.pipepie.DashboardTokenReqH\x00R\fdashTokenReq\x12E\n" +
	"\x0fdash_token_resp\x18\n" +
	" \x01(\v2\x1b.pipepie.DashboardTokenRespH\x00R\rdashTokenRespB\t\n" +
	"\apayload\"\x13\n" +
	"\x11DashboardTokenReq\"<\n" +
	"\x12DashboardTokenResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"T\n" +
	"\x04Auth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1c\n" +
	"\tsubdomain\x18\x02 \x01(\tR\tsubdomain\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"E\n" +
	"\x06AuthOK\x12\x1c\n" +
	"\tsubdomain\x18\x01 \x01(\tR\tsubdomain\x12\x1d\n" +
	"\n" +
	"public_url\x18\x02 \x01(\tR\tpublicUrl\"%\n" +
	"\tAuthError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa9\x02\n" +
	"\vHttpRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12;\n" +
	"\aheaders\x18\x05 \x03(\v2!.pipepie.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12\x1e\n" +
	"\n" +
	"compressed\x18\a \x01(\bR\n" +
	"compressed\x12\x1b\n" +
	"\treplay_of\x18\b \x01(\tR\breplayOf\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\fHttpResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12<\n" +
	"\aheaders\x18\x03 \x03(\v2\".pipepie.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1e\n" +
	"\n" +
	"compressed\x18\x05 \x01(\bR\n" +
	"compressed\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\fForwardError\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04PongB6Z4github.com/Seinarukiro2/pipepie/internal/protocol/pbb\x06proto3"

var (
	file_wire_proto_rawDescOnce sync.Once
	file_wire_proto_rawDescData []byte
)

func file_wire_proto_rawDescGZIP() []byte {
	file_wire_proto_rawDescOnce.Do(func() {
		file_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)))
	})
	return file_wire_proto_rawDescData
}

var file_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_wire_proto_goTypes = []any{
	(*Frame)(nil),              // 0: pipepie.Frame
	(*DashboardTokenReq)(nil),  // 1: pipepie.DashboardTokenReq
	(*DashboardTokenResp)(nil), // 2: pipepie.DashboardTokenResp
	(*Auth)(nil),               // 3: pipepie.Auth
	(*AuthOK)(nil),             // 4: pipepie.AuthOK
	(*AuthError)(nil),          // 5: pipepie.AuthError
	(*HttpRequest)(nil),        // 6: pipepie.HttpRequest
	(*HttpResponse)(nil),       // 7: pipepie.HttpResponse
	(*ForwardError)(nil),       // 8: pipepie.ForwardError
	(*Ping)(nil),               // 9: pipepie.Ping
	(*Pong)(nil),               // 10: pipepie.Pong
	nil,                        // 11: pipepie.HttpRequest.HeadersEntry
	nil,                        // 12: pipepie.HttpResponse.HeadersEntry
}
var file_wire_proto_depIdxs = []int32{
	3,  // 0: pipepie.Frame.auth:type_name -> pipepie.Auth
	4,  // 1: pipepie.Frame.auth_ok:type_name -> pipepie.AuthOK
	5,  // 2: pipepie.Frame.auth_error:type_name -> pipepie.AuthError
	6,  // 3: pipepie.Frame.request:type_name -> pipepie.HttpRequest
	7,  // 4: pipepie.Frame.response:type_name -> pipepie.HttpResponse
	8,  // 5: pipepie.Frame.forward_error:type_name -> pipepie.ForwardError
	9,  // 6: pipepie.Frame.ping:type_name -> pipepie.Ping
	10, // 7: pipepie.Frame.pong:type_name -> pipepie.Pong
	1,  // 8: pipepie.Frame.dash_token_req:type_name -> pipepie.DashboardTokenReq
	2,  // 9: pipepie.Frame.dash_token_resp:type_name -> pipepie.DashboardTokenResp
	11, // 10: pipepie.HttpRequest.headers:type_name -> pipepie.HttpRequest.HeadersEntry
	12, // 11: pipepie.HttpResponse.headers:type_name -> pipepie.HttpResponse.HeadersEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_wire_proto_init() }
func file_wire_proto_init() {
	if File_wire_proto != nil {
		return
	}
	file_wire_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Auth)(nil),
		(*Frame_AuthOk)(nil),
		(*Frame_AuthError)(nil),
		(*Frame_Request)(nil),
		(*Frame_Response)(nil),
		(*Frame_ForwardError)(nil),
		(*Frame_Ping)(nil),
		(*Frame_Pong)(nil),
		(*Frame_DashTokenReq)(nil),
		(*Frame_DashTokenResp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_proto_goTypes,
		DependencyIndexes: file_wire_proto_depIdxs,
		MessageInfos:      file_wire_proto_msgTypes,
	}.Build()
	File_wire_proto = out.File
	file_wire_proto_goTypes = nil
	file_wire_proto_depIdxs = nil
}
